MODULE NOSE_HOOVER

  ! -- THIS MODULE CONTAINS THE VARIABLES OF A NOSE HOOVER CHAIN
  ! -- THE SELECTION OF THE PARAMETERS ARE BASED ON THE PAPER
  ! -- `G. J. MARTYNA ET AL, MOL. PHYS. 1996 (87) 1117.
  ! -- XIANTAO

  USE CMM_PARMS

  IMPLICIT NONE

  PUBLIC

  ! -- NUMBER OF ATOMS IN THE NOSE HOOVER CHAIN
  INTEGER, PARAMETER :: NNOS=10, NNOS1= NNOS+1

  ! -- (Nys IN THE PAPER)
  INTEGER, PARAMETER :: NYOSH=5

  ! -- THE NUMBER OF FRACTIONAL STEPS (nc IN THE PAPER)
  INTEGER, PARAMETER :: NRESN=2

  ! -- TEMPERATURE KT, AND Nf*KT
  
  REAL(8) :: GKT, GNKT

  ! -- POSITION AND VELOCITY OF THE NH ATOMS
  REAL(8) :: XLOGS(NNOS), VLOGS(NNOS)
  
  ! -- FORCE AND MASS OF THE NH ATOMS
  REAL(8) :: GLOGS(NNOS), QMASS(NNOS)

  ! -- PARAMETERS IN EACH FRACTIONAL STEP OF THE INTEGRATION 
  REAL(8) :: DT2, DT22
  REAL(8), DIMENSION(NYOSH) :: WNH, WDTI, WDTI2, WDTI4, WDTI8

END MODULE NOSE_HOOVER
