T: 1
batch_size: 2048
beta1: 0.9
d: 3
d_max: 5
depth: 3
eps: 1.0e-08
grad_clip: -1
grid_step: 1.0
k0: 3.6
lr_sde: 0.0001
lr_train: 0.001
max_grid: 2.0
max_sam: 2.0
min_grid: -2.0
min_sam: -2.0
model:
  name: ScoreNet
  num_scales: 50
  sigma_max: 0.2
  sigma_min: 0.01
n_all: 125
n_all_per_dim: 5
n_epochs: 10
n_sam: 125
n_sam_per_dim: 5
n_steps: 50
nd: 375
ntrajs_sample: 20000
ntrajs_train: 50000
optimizer: Adam
path_checkpoints: ./output/20250122_011408_N125_n125_d3/checkpoints
path_output: ./output/20250122_011408_N125_n125_d3/
path_params: ./output/20250122_011408_N125_n125_d3/params
print_interval: 20
sampler:
  method: em
save_interval: 100
sigma_DSM: 1
training:
  sde: vesde
use_bn: false
warmup: 0
weight_decay: 0
width: 512
