net:
  depth: 4
  width: 256
  use_bn: False

data:
  cfg_flag: 1
  problem: 'quadratic_potential'
  # problem: 'fe211'
  crystal: 'SC'
  # crystal: 'BCC'
  d: 1
  nx_max:
  na: 2
  nx: 4
  ny:
  nz:
  n_max:
  n:
  nf:
  defm: 
  - - 1.0
  # defm:
  # - - 1.0
  #   - 0.0
  #   - 0.0
  # - - 0.0
  #   - 1.0
  #   - 0.0
  # - - 0.0
  #   - 0.0
  #   - 1.0
  grid_step: 0.1
  min_grid: 
  max_grid: 
  min_x: 
  max_x: 
  train_data_dirs: '../SAM_dataset/traindata/'
  eval_data_dir: '../SAM_dataset/evaldata/150_01/'
  delete_rawdata: False

optim:
  optimizer: 'Adam'
  lr: 5.0e-4
  beta1: 0.9
  eps: 1.0e-8
  weight_decay: 0
  warmup: 1000
  grad_clip: 1

model:
  name: 'NCSNpp'
  cond_dim: 1
  sigma_min: 0.01
  sigma_max: 0.3
  beta_min: 0.01
  beta_max: 0.05
  dropout: 0.1
  T: 1.0
  num_scales: 2000
  nonlinearity: 'swish'
  nf: 32
  ch_mult: [1, 2, 4, 8]
  num_res_blocks: 0
  attn_resolutions: [16,]
  resamp_with_conv: True
  conditional: True
  fir: False
  fir_kernel: [1, 3, 3, 1]
  skip_rescale: True
  embedding_type: 'fourier'
  resblock_type: 'ddpm'
  progressive: 'output_skip'
  progressive_input: 'output_skip'
  progressive_combine: 'sum'
  init_scale: 0.
  fourier_scale: 16

dynamics:
  k0: 3.6
  k_near: 5

training:
  sde: 'vpsde'
  ntrajs: 300000
  batch_size: 3072
  n_iter: 5000
  initial_step: 0
  continuous: True
  reduce_mean: False
  likelihood_weighting: False

sampler:
  method: 'em'
  ntrajs: 20000
  snr: 0.17
  predictor: 'em'
  corrector: 'none'

log:
  print_interval: 20
  save_interval: 1000
  verbose: False

path:
  output:
  checkpoints:
  eval:
  params:

eval:
  temperature: 300.0
  stress_cond: '02'
  cond: '300_02'