net:
  depth: 4
  width: 256
  use_bn: False

data:
  cfg_flag: 1
  d: 1
  nx_max: 50
  nx: 5
  n_max:
  n:
  nd: 
  grid_step: 0.1
  min_grid: 
  max_grid: 
  min: 
  max_sam: 

optim:
  optimizer: 'Adam'
  lr: 5.0e-4
  beta1: 0.9
  eps: 1.0e-8
  weight_decay: 0
  warmup: 0
  grad_clip: -1

model:
  name: 'ResNet'
  sigma_min: 0.01
  sigma_max: 0.3
  beta_min: 0.01
  beta_max: 0.05
  dropout: 0.1
  T: 1.0
  num_scales: 5000
  k0: 3.6
  temperature: 1.0
  k_near: 5
  nonlinearity: 'swish'
  nf: 128
  ch_mult: [1, 1, 2, 2, 2, 2, 2]
  num_res_blocks: 1
  attn_resolutions: [16,]
  resamp_with_conv: True
  conditional: True
  fir: True
  fir_kernel: [1, 3, 3, 1]
  skip_rescale: True
  embedding_type: 'fourier'
  resblock_type: 'ddpm'
  progressive: 'output_skip'
  progressive_input: 'output_skip'
  progressive_combine: 'sum'
  init_scale: 0.
  fourier_scale: 16

training:
  sde: 'vpsde'
  ntrajs: 50000
  batch_size: 2048
  n_iter: 5000
  initial_step: 0
  continuous: True
  reduce_mean: False
  likelihood_weighting: False

sampler:
  method: 'em'
  ntrajs: 20000
  snr: 0.17

log:
  print_interval: 20
  save_interval: 1000
  verbose: False

path:
  output:
  checkpoints:
  eval:
  params: