net:
  depth: 4
  width: 256
  use_bn: False

data:
  cfg_flag: 1
  # problem: 'quadratic_potential'
  problem: 'fe211'
  # crystal: 'SC'
  crystal: 'BCC'
  d:
  nx_max:
  nx: 4
  n_max:
  n:
  nf: 
  grid_step:
  min_grid: 
  max_grid: 
  min_sam: 
  max_sam: 
  data_dir: 'data6/'
  delete_rawdata: False

optim:
  optimizer: 'Adam'
  lr: 5.0e-4
  beta1: 0.9
  eps: 1.0e-8
  weight_decay: 0
  warmup: 0
  grad_clip: -1

model:
  name: 'NCSNpp'
  sigma_min: 0.01
  sigma_max: 0.3
  beta_min: 0.01
  beta_max: 0.05
  dropout: 0.1
  T: 1.0
  num_scales: 2000
  nonlinearity: 'swish'
  nf: 32
  ch_mult: [1, 2, 4, 8]
  num_res_blocks: 0
  attn_resolutions: [16,]
  resamp_with_conv: True
  conditional: True
  fir: False
  fir_kernel: [1, 3, 3, 1]
  skip_rescale: True
  embedding_type: 'fourier'
  resblock_type: 'ddpm'
  progressive: 'output_skip'
  progressive_input: 'output_skip'
  progressive_combine: 'sum'
  init_scale: 0.
  fourier_scale: 16

dynamics:
  k0: 3.6
  temperature: 1.0
  k_near: 5

training:
  sde: 'vpsde'
  ntrajs: 20000
  batch_size: 2048
  n_iter: 100
  initial_step: 1000
  continuous: True
  reduce_mean: False
  likelihood_weighting: False

sampler:
  method: 'em'
  ntrajs: 10000
  snr: 0.17

log:
  print_interval: 20
  save_interval: 1000
  verbose: False

path:
  output: './output/20250304_232443_N432_n432_k5_d3'
  checkpoints:
  eval:
  params: